include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
    avoid_positional_boolean_parameters: false
    public_member_api_docs: false
    constant_identifier_names: false
    prefer_mixin: false
